/* TRIM FUNCTION */
/* TO REMOVE LEADING SPACE */
SELECT TRIM(LEADING ' ' FROM'  STAR-TECH ACADEMY   ');
/* TO REMOVE TRAILING SPACE */
SELECT TRIM(TRAILING ' ' FROM '    STAR-TECH ACADEMY  ');
/* TO REMOVE BOTH SIDE SPACE */
SELECT TRIM(BOTH ' ' FROM'    STAR-TECH ACADEMY   ');
SELECT TRIM('    STAR-TECH ACADEMY   ');

/* RTRIM */
SELECT rtrim('    STAR-TECH ACADEMY    ','   ');
/* LTRIM */
SELECT ltrim('     STAR-TECH ACADEMY  ','   ');